### ISSUE TITLE
Can you provide more documentation?

### ISSUE THREAD

**Issue by untotren** [xsteadfastx/mopidy-emby#2]
I realize this is new but this is awesome and i would like to read more.

I have wanted to have music on my website, hosted like an html5 player, embedded.  Is that something this can do?  If so, what port does it run on?  Sorry I am a bit of a newb idk if this accomplishes that.

**Comment by xsteadfastx** [comment]
mopidy is a music daemon. it connects to some audio output and some libraries. for example local files or with this plugin to a emby library. it runs headless and you can control it through alot of interfaces. also html5 web interfaces or command line tools.
