### ISSUE TITLE
Can it provide media library?

### ISSUE THREAD

**Issue by sivakov512** [xsteadfastx/mopidy-emby#3]
Hello!
I use `mopidy` and `ncmpcpp` as player for this. After installing this plugin I see `Filesystem provider` `[emby]` in `ncmpcpp` interface, but `Library` is empty. Can it provide `Library` "interface"?
If not, how to implement this? Maybe you can consult me with API or any other help?

Thank you,
Sorry for my bad English.

**Comment by xsteadfastx** [comment]
Strange. You have a music defined library? The plugin looks for that. Can you start mopidy in debug mode and paste the logs?

**Comment by sivakov512** [comment]
Sorry, but what you mean at "music defined library"?

**Comment by xsteadfastx** [comment]
could you run `mopidy -v` and try to access the emby library through mopidy and paste the log? that would help alot. normally if there is no music library in emby it throws a exception and prints what libraries got found. at least thats how i coded it in ;-)

**Comment by sivakov512** [comment]
Sorry for long reaction.
I dont use emby now so I dont have a problem :)
